
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 328854
  host: localhost
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_task_development

 
test:
  <<: *default
  database: app_task_test


production:
  <<: *default
  database: app_task_production
  username: app_task
  password: <%= ENV["APP_TASK_DATABASE_PASSWORD"] %>
